---
name: Push an Ansible role to Galaxy
description: Push an Updated Ansible role to Ansible Galaxy
author: Open Microscopy Environment

branding:
  icon: server
  color: yellow

inputs:
  galaxy-api-key:
    description: Ansible galaxy API key
    required: true
  galaxy-version: 
    description: The version to push to Ansible galaxy
    required: true
  role-name:
    description: The name of the role
    required: true


runs:
  using: composite
  steps:
    - name: Import role
      run: ansible-galaxy role import -vvv --api-key ${{ inputs.galaxy-api-key }}  --branch ${{ inputs.galaxy-version }}  --role-name=${{ inputs.role-name }} ${GITHUB_REPOSITORY%/*} ${GITHUB_REPOSITORY#*/}
      shell: bash
